package model

import "errors"

var (
	ErrNotFound               = errors.New("task not found")
	ErrEmptyTitle             = errors.New("empty title")
	ErrInvalidID              = errors.New("invalid ID")
	ErrAlreadyDone            = errors.New("task already done")
	ErrAlreadyUndone          = errors.New("task already undone")
	ErrNotImplemented         = errors.New("not implemented")
	ErrNotDone                = errors.New("task not done")
	ErrNothingToUpdate        = errors.New("nothing to patch")
	ErrTitleTooLong           = errors.New("title too long")
	ErrNotAllowed             = errors.New("operation not allowed")
	ErrMissingDBURL           = errors.New("missing database URL")
	ErrInvalidShutdownTimeout = errors.New("invalid shutdown timeout")
	ErrInvalidDate            = errors.New("invalid date, want YYYY-MM-DD")
	ErrProjectNotFound        = errors.New("project not found")
	ErrSubtaskTooDeep         = errors.New("subtasks can only be one level deep")
	ErrInvalidView            = errors.New("invalid view")
	ErrInvalidQuery           = errors.New("invalid query parameter")
	ErrInvalidBody            = errors.New("invalid request body")
	ErrInvalidPriority        = errors.New("invalid priority, want high|medium|low")
	ErrEmptyName              = errors.New("empty name")
	ErrInvalidColor           = errors.New("invalid color, want #RRGGBB")
	ErrUnauthorized           = errors.New("login required")
	ErrWrongPassword          = errors.New("wrong password")
	ErrInvalidRepeat          = errors.New("invalid repeat rule, want daily|weekdays|weekly:1,4|monthly:15")
)
